//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veb_portal_za_aukcijsku_prodaju.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bid()
        {
            this.Aukcijas = new HashSet<Aukcija>();
        }
    
        public int BidID { get; set; }
        public Nullable<double> PonCena { get; set; }
        public Nullable<System.DateTime> Vreme { get; set; }
        public int KorisnikID { get; set; }
        public int AukcijaID { get; set; }
    
        public virtual Aukcija Aukcija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aukcija> Aukcijas { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
